class ExistingUserError(Exception):
    pass


class ExistingMachineError(Exception):
    pass
